/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#d4af37",
        "tertiary-fixed": "#dbe1ff",
        "tertiary": "#415ba4",
        "on-tertiary-container": "#254188",
        "on-primary-container": "#554300",
        "on-tertiary-fixed": "#00174b",
        "secondary-container": "#ff8e81",
        "on-surface-variant": "#4d4635",
        "outline": "#7f7663",
        "surface-container-highest": "#e5e2e1",
        "heritage-gold": "#D4AF37",
        "on-tertiary-fixed-variant": "#27438a",
        "regal-burgundy": "#4A0404",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "antique-cream": "#F9F6F0",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container": "#f0edec",
        "secondary-fixed": "#ffdad5",
        "surface-dim": "#dcd9d9",
        "surface-variant": "#e5e2e1",
        "on-secondary-container": "#77251f",
        "on-surface": "#1c1b1b",
        "on-primary-fixed": "#241a00",
        "surface-tint": "#735c00",
        "outline-variant": "#d0c5af",
        "tertiary-container": "#97b0ff",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#7e2b23",
        "background": "#fcf9f8",
        "on-secondary-fixed": "#410001",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#e9c349",
        "deep-onyx": "#121212",
        "inverse-primary": "#e9c349",
        "surface": "#fcf9f8",
        "secondary-fixed-dim": "#ffb4aa",
        "secondary": "#9d4139",
        "on-primary-fixed-variant": "#574500",
        "inverse-on-surface": "#f3f0ef",
        "surface-container-high": "#ebe7e7",
        "primary": "#735c00",
        "on-background": "#1c1b1b",
        "tertiary-fixed-dim": "#b4c5ff",
        "inverse-surface": "#313030",
        "surface-container-low": "#f6f3f2",
        "error-container": "#ffdad6",
        "primary-fixed": "#ffe088",
        "on-secondary": "#ffffff",
        "surface-bright": "#fcf9f8"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        gutter: "24px",
        "container-max": "1280px",
        "section-gap": "80px",
        unit: "8px"
      },
      fontFamily: {
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
